# Generated by Django 3.2.15 on 2022-08-13 17:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
