# Generated by Django 3.2.15 on 2022-08-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='picture',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
