# Generated by Django 3.2.15 on 2022-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20220824_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_id',
            field=models.IntegerField(default=0),
        ),
    ]
