# Generated by Django 3.2.15 on 2022-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='colour',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Saloon', 'Saloon'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Estate', 'Estate'), ('SUV', 'SUV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Bmw', 'Bmw'), ('Citroën', 'Citroën'), ('Ford', 'Ford'), ('Mazda', 'Mazda'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Opel', 'Opel'), ('Lexus', 'Lexus'), ('Mercedes', 'Mercedes'), ('Volkswagen', 'Volksvagen'), ('Volvo', 'Volvo')], max_length=50),
        ),
    ]
