# Generated by Django 3.2.15 on 2022-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_engine_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='owners',
            field=models.IntegerField(),
        ),
    ]
