# Generated by Django 3.2.15 on 2022-08-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20220813_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body',
        ),
        migrations.RemoveField(
            model_name='car',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='car',
            name='date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_size',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='milage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
