# Generated by Django 3.2.15 on 2022-08-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20220814_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
