# Generated by Django 3.2.15 on 2022-08-21 13:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_hire_date'),
        ('cars', '0008_car_is_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='nct',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='car',
            name='previous_owners',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='road_tax',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='sales_person',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee'),
        ),
    ]
