# Generated by Django 3.2.15 on 2022-08-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_hire_date'),
        ('cars', '0009_auto_20220821_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sales_person',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee'),
        ),
    ]
