# Generated by Django 3.2.15 on 2022-09-08 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='nct',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
