# Generated by Django 3.2.15 on 2022-09-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_nct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Bmw', 'Bmw'), ('Citroen', 'Citroen'), ('Ford', 'Ford'), ('Kia', 'Kia'), ('Mazda', 'Mazda'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Opel', 'Opel'), ('Lexus', 'Lexus'), ('Mercedes', 'Mercedes'), ('Volkswagen', 'Volksvagen'), ('Volvo', 'Volvo')], default='Audi', max_length=50),
        ),
    ]
